intro_task:
  description: >
    Démarrer l'entretien pour le poste {role_title} chez {company_name} avec {candidate_name}. Présente le cadre (durée ~45min, sections: intro, technique, soft skills, feedback, conclusion),
    rappelle la confidentialité, demande le consentement et confirme la compréhension du candidat.
    Utilise AskCandidateTool pour poser EXACTEMENT 1 SEULE question introductive concise et recueillir la réponse. Adresse le candidat par son nom (« {candidate_name} »). Passe ensuite au bloc technique.
    IMPORTANT: Tu ne dois poser qu'UNE SEULE question d'introduction, pas plus.
  expected_output: >
    JSON {"intro_questions": [{"q": str, "a": str}], "consent": true|false}
  agent: intro_agent

tech_qna_task:
  description: >
    Conduire la partie technique. Utilise exclusivement le RAG via l'outil RAGSearchTool pour formuler EXACTEMENT 5 questions techniques, ni plus ni moins.
    Chaque question DOIT citer au moins un chunk_id et inclure un court contexte extrait du chunk.
    POUR CHAQUE QUESTION, tu DOIS appeler AskCandidateTool pour poser la question et collecter la réponse du candidat avant de passer à la suivante.
    IMPORTANT: Tu dois poser strictement 5 questions techniques, pas plus, pas moins.
  expected_output: >
    JSON {"tech_qa": [{"q": str, "a": str, "chunk_id": str}], "count": 5}
  agent: tech_interviewer

softskills_qna_task:
  description: >
    Conduire la partie soft skills avec EXACTEMENT 5 questions comportementales (STAR/SAO), ni plus ni moins.
    POUR CHAQUE QUESTION, tu DOIS appeler AskCandidateTool pour poser la question et collecter la réponse.
    CONTRAINTE STRICTE: Après avoir posé exactement 5 questions, tu DOIS immédiatement arrêter et produire le JSON final.
    IMPORTANT: Tu dois poser strictement 5 questions de soft skills, pas plus, pas moins. Compte chaque question posée.
  expected_output: >
    JSON {"soft_qa": [{"q": str, "a": str}], "count": 5}
  agent: softskills_interviewer

analysis_scoring_task:
  description: >
    Analyser les réponses. Côté technique: comparer les réponses aux contenus RAG cités, évaluer précision, complétude, exactitude factuelle.
    Côté soft skills: évaluer pertinence, clarté, structure, collaboration, ownership. Produire deux scores 0-100 et justification brève.
  expected_output: >
    JSON {"technical_score": int, "technical_comment": str, "soft_skills_score": int, "soft_skills_comment": str}
  agent: analyst_agent

report_task:
  description: >
    Générer le rapport final pour recruteur non technique: résumé du profil, liste des questions et réponses, scores, points forts,
    axes d'amélioration, recommandation finale (Oui/Non/A discuter) avec justification.
  expected_output: >
    1) Un bloc JSON (une seule ligne) respectant exactement la structure:
    {"profile_summary":"...","technical_score":0,"technical_comment":"...","soft_skills_score":0,"soft_skills_comment":"...","strengths":["..."],"improvements":["..."],"final_recommendation":"Oui|Non|A discuter","recommendation_reason":"..."}
    2) Ensuite, un rapport complet en Markdown, sans balises ```.
  agent: reporter_agent
